apiVersion: v1
kind: Pod
metadata:
  name: movie-client
spec:
  containers:
  - name: movie-client
    image: ehddnr/movie-recommand:movie-client
    imagePullPolicy: Always
    env:
    - name: REQUEST_URL
      valueFrom:
        secretKeyRef:
          name: client-secret
          key: request_url
    - name: GITHUB_URL
      valueFrom:
        secretKeyRef:
          name: client-secret
          key: github_url