{
 "title": "대시보드",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "개봉한 영화 수",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct movie_id)\nfrom movies ;"
    }
   ]
  },
  {
   "title": "유저 만족도 현황",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 15, "x": 5, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT user_type,\ndate_trunc('minute', created_at) AS \"time\",\n SUM(score) AS \"Group\"\nFROM feedbacks \nwhere $__timeFilter(created_at)\nGROUP BY user_type, date_trunc('minute', created_at)\n order by time"
    }
   ]
  },
  {
   "title": "최근 개봉 영화의 평균 평점",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select rating\nfrom ratings\nwhere movie_id in (\n  select movie_id\n  from movies \n  where $__timeFilter(created_at)\n  order by created_at desc\n  limit 1\n)\nand $__timeFilter(created_at)"
    }
   ]
  },
  {
   "title": "피드백에 참여한 유저 수",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT user_id)\nFROM feedbacks;"
    }
   ]
  },
  {
   "title": "A/A Test 유저 그룹별 평균 만족도",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT user_type,\n AVG(score)\nFROM feedbacks \nwhere action_cycle = 0\nand $__timeFilter(created_at)\nGROUP BY user_type "
    }
   ]
  },
  {
   "title": "A/B Test 유저 그룹별 평균 만족도",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT user_type,\n AVG(score)\nFROM feedbacks \nwhere action_cycle = 1\nand $__timeFilter(created_at)\nGROUP BY user_type "
    }
   ]
  },
  {
   "title": "\b평균 서비스 만족도 순 랭킹",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT \n    m.title as \"영화 제목\",\n    AVG(r.rating) as \"평균 평점\",\n    AVG(f.score) as \"서비스 만족도\",\n    COUNT(*) as \"시청 유저 수\"\nFROM \n    ratings r\nJOIN \n    movies m ON r.movie_id = m.movie_id\nJOIN\n    feedbacks f ON r.movie_id = f.selected_movie_id\nWHERE $__timeFilter(f.created_at)\nGROUP BY \n    r.movie_id, m.title\nHAVING COUNT(*) > 10\nORDER BY \n    \"서비스 만족도\" DESC\n\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT user_type,\ndate_trunc('minute', created_at) AS \"time\",\n SUM(score) AS \"Group\"\nFROM feedbacks \nwhere action_cycle = 0\nand $__timeFilter(created_at)\nGROUP BY user_type, date_trunc('minute', created_at)\n order by time"
    },
    {
     "rawSql": "SELECT user_type,\ndate_trunc('minute', created_at) AS \"time\",\n SUM(score) AS \"Group\"\nFROM feedbacks \nwhere action_cycle = 1\nand $__timeFilter(created_at)\nGROUP BY user_type, date_trunc('minute', created_at)\n order by time"
    }
   ]
  }
 ]
}