

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-dashboard-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-dashboard
  template:
    metadata:
      labels:
        app: grafana-dashboard
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: grafana-secret
              key: grafana-user
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-secret
              key: grafana-password
        - name: GF_DASHBOARDS_MIN_REFRESH_INTERVAL
          value: "500ms"

---

apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: NodePort
  selector:
    app: grafana-dashboard
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30085