apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: ehddnr/movie-recommand:fastapi
        imagePullPolicy: Always
        env:
        - name: ENV
          valueFrom:
            secretKeyRef:
              name: fastapi-secret
              key: env
        - name: MLFLOW_TRACKING_URI
          valueFrom:
            secretKeyRef:
              name: fastapi-secret
              key: mlflow_tracking_uri
        - name: MLFLOW_S3_ENDPOINT_URL
          valueFrom:
            secretKeyRef:
              name: mlflow-secret
              key: mlflow-s3-endpoint-url
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: mlflow-secret
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mlflow-secret
              key: aws-secret-access-key
        - name: TEST_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: fastapi-secret
              key: test_database_url
        - name: PROD_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: fastapi-secret
              key: prod_database_url
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: NodePort
  selector:
    app: fastapi
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30084