apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs-pv
spec:
  storageClassName: nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /home/${USER}/logs
    server: ${SERVER_IP}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: airflow-logs-pv  # 사용할 PV 이름