apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      initContainers:
      - name: airflow-db-init
        image: ehddnr/movie-recommand:airflow
        command: ["airflow", "db", "init"]
        env:
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          valueFrom:
            secretKeyRef:
              name: airflow-secret
              key: airflow-core-sql-alchemy-conn
      - name: airflow-users-create
        image: ehddnr/movie-recommand:airflow
        command: ["airflow", "users", "create", "-u", "admin", "-p", "admin", "-r", "Admin", "-e", "admin@admin.com", "-f", "admin", "-l", "admin"]
        env:
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          valueFrom:
            secretKeyRef:
              name: airflow-secret
              key: airflow-core-sql-alchemy-conn
      containers:
        - name: airflow-webserver
          image: ehddnr/movie-recommand:airflow
          ports:
            - name: web
              containerPort: 8080
          env:
          - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
            valueFrom:
              secretKeyRef:
                name: airflow-secret
                key: airflow-core-sql-alchemy-conn
          - name: AIRFLOW__CORE__DAGS_FOLDER
            value: "/opt/airflow/dags/etl-dags"
          command: ["airflow"]
          args:
            - "webserver"
            - "--port"
            - "8080"
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags
            - name: logs
              mountPath: /opt/airflow/logs

        - name: git-sync
          securityContext:
            runAsUser: 50000
          image: registry.k8s.io/git-sync/git-sync:v3.6.3
          env:
            - name: GIT_SYNC_REPO
              value: "https://github.com/ehddnr301/MovieRecommender-DAGs.git"
            - name: GIT_SYNC_ROOT
              value: "/opt/airflow/dags"
            - name: GIT_SYNC_BRANCH
              value: "main"
            - name: GIT_SYNC_DEST
              value: "etl-dags"
            - name: GIT_SYNC_DEPTH
              value: "1"
            - name: GIT_SYNC_PERIOD
              value: "60s"
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags

      volumes:
        - name: dags
          emptyDir: {}
        - name: logs
          persistentVolumeClaim:
            claimName: airflow-logs-pvc

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
        - name: airflow-scheduler
          image: ehddnr/movie-recommand:airflow
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-secret
                  key: airflow-core-sql-alchemy-conn
            - name: AIRFLOW__CORE__DAGS_FOLDER
              value: "/opt/airflow/dags/etl-dags"
          args:
            - scheduler
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags
            - name: logs
              mountPath: /opt/airflow/logs

        - name: git-sync
          securityContext:
            runAsUser: 50000
          image: registry.k8s.io/git-sync/git-sync:v3.6.3
          env:
            - name: GIT_SYNC_REPO
              value: "https://github.com/ehddnr301/MovieRecommender-DAGs.git"
            - name: GIT_SYNC_ROOT
              value: "/opt/airflow/dags"
            - name: GIT_SYNC_BRANCH
              value: "main"
            - name: GIT_SYNC_DEST
              value: "etl-dags"
            - name: GIT_SYNC_PERIOD
              value: "60s"
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags

      volumes:
        - name: dags
          emptyDir: {}
        - name: logs
          persistentVolumeClaim:
            claimName: airflow-logs-pvc


---

apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver-service
spec:
  type: NodePort
  selector:
    app: airflow-webserver
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081

---

apiVersion: v1
kind: Service
metadata:
  name: airflow-scheduler
spec:
  selector:
    app: airflow-scheduler
  ports:
    - name: scheduler
      protocol: TCP
      port: 8793